// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using restCadastro.Data;

namespace restCadastro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210721163141_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("restCadastro.Data.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Email")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Analista de Sistemas I",
                            Email = "Lucas.cordeiro@totvs.br",
                            Nome = "Lucas Cordeiro"
                        },
                        new
                        {
                            Id = 2,
                            Cargo = "Analista de Infra I",
                            Email = "Joabe.Queiroz@totvs.br",
                            Nome = "Joabe Queiroz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
